jazzband/django-constance

tox.ini

Should fix #110
Workaround for the partially-fixed pypa/pip#1473, letting tests on django master work again.

Work around for pip bug w/ Django zips

---

constance/models.py
tox.ini

Simple fix for the dropping of 'name' from ContentType in Django 1.8

[Fixes #93] Make models.py 1.8 compatible

---

constance/backends/database/__init__.py
constance/models.py
constance/templates/admin/constance/change_list.html
constance/utils.py
tox.ini

* Add Django 1.8 to test environments in tox.ini
* Update python versions supported by Django master in tox.ini
* Don't load 'url' from template library 'future' - it is no longer
available in Django master, and is not needed in Django 1.4 and later,
which is as far back as django-constance tests
* get_cache dropped from Django master
* post_syncdb signal dropped
* django.utils.importlib dropped
There are still errors on some environments that I didn't try to
address:
* coverage seems broken on py32
* django-master seems currently broken on py27 (non-ASCII character somewhere,
I expect django-master will be fixed soon since they still claim py27 support)
* django14 seems broken: "NoReverseMatch: u"'admin" is not a registered
namespace"

Some fixes for recent Djangos

---

constance/admin.py
constance/apps.py
constance/backends/database/__init__.py
constance/connect.py
constance/templates/admin/constance/change_list.html
constance/utils.py
tests/test_admin.py
tests/urls.py
tox.ini

Drop python 2.6
Drop Django 1.4, 1.5, 1.6
Remove models.py under constance and move to an appconfig imported file.
This is a bit more aggressive of a compatibility change compared to previous PR's.

Compatibility changes.

---

constance/test/__init__.py
constance/test/utils.py
docs/index.rst
docs/testing.rst
tests/test_test_utils.py

This PR adds an `override_config` decorator that mirrors Django's `override_settings` decorator for use in testing. It allows users of the app to easily test how their application responds to changes in the values of `config` parameters.
I have added a `TestCase` and confirmed the functionality across the supported Python and Django versions using tox locally. This PR should introduce no more failing tests than currently exist in the master branch.
I've also updated the docs accordingly. Thanks for taking a look!

Add override_config class for testing config values

---

tox.ini

I couldn't find anything relating to Django 1.9 support, since there's a stable release I thought let's add it to tox.ini explicitly.
https://docs.djangoproject.com/en/1.9/releases/1.9/

Update tox.ini to test for Django 1.9

---

constance/admin.py
constance/templates/admin/constance/change_list.html

The new admin style for Django 1.9 has replaced its gif icons for svg versions.

Replace removed gif icons with svg versions

---

constance/admin.py
docs/index.rst

I moved the form class for constance to a property of the Admin, similar to the form property in the default Model Admin, but gave it a different name in case the actual form will be used in some kind of detailed settings view in the future.
This allows to easily customize the Form used by Constance for rendering the settings, by simply subclassing ConstanceAdmin and ConstanceForm.

Moved ConstanceForm to a property to make it exchangable by inheritance

---

docs/index.rst

Code examples aren't rendering currently on http://django-constance.readthedocs.org/en/latest/#custom-fields due to missing line at the start of code-blocks.

Fix formatting of CONSTANCE_ADDITIONAL_FIELDS doc

---

constance/admin.py
docs/index.rst
tests/settings.py
tests/storage.py

Allow the field config to be a tuple, and allow the config dict to be omitted.

Make CONSTANCE_ADDITIONAL_FIELDS more flexible

---

constance/admin.py
docs/index.rst

The name of the variable has missing "CONSTANCE_" string at the begining

Typo on the variable name of verification hash version

---

constance/admin.py

https://docs.djangoproject.com/en/1.9/releases/1.9/#removed-features-1-9
The ability to use a SplitDateTimeWidget with DateTimeField is removed.
Update to use SplitDateTimeField instead. Cheers.

Use SplitDateTimeField instead of DateTimeField

---

README.rst
docs/changes.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

docs/backends.rst

`redis_cache` is deprecated, and updated to `django_redis` from version of 3.9.x
http://niwinz.github.io/django-redis/latest/

Update connection class string for django redis

---

constance/backends/database/__init__.py

Hi,
all constance values are set into cache in autofill() method on the constance start. 
All values are set in the same time and their expires in the same time.
After constance cache expires, next time a code ask for constance value, the value is set back into cache.
So constance re-fills cache value be value, one be one, but it causes a lot of unnecessary db calls. 
I want to autofill all constance values into cache in the same time to save db queries. 
This problem is way more obvious when DATABASE_CACHE_AUTOFILL_TIMEOUT is very small.

autofill cache if key is missing.

---

constance/admin.py

I found an scenario working with other django projects where the Meta for a model needs to have the `app_config` property as any other django.db.models.Model.Meta.

Add app_config property to Config.Meta

---

constance/admin.py
constance/templates/admin/constance/change_list.html

An application user who wants to use an app under a different name would normally override the configuration. This is explained in the [Django documentation](https://docs.djangoproject.com/en/1.10/ref/applications/#for-application-users).
To use _Constance_ under the _Setup_ name, the following can be added to `apps.py`:
```python
import constance.apps
class RenameConstanceConfig(constance.apps.ConstanceConfig):
verbose_name = 'Setup'
verbose_name_plural = 'Setup'
```
This does not work as expected and will still leave _constance_ strings laying around since the config is [hard-coded](https://github.com/jazzband/django-constance/blob/dd173cd42cb9351285163fde5101975862c5ebfa/constance/admin.py#L261) and the _constance_ string is [hard-coded](https://github.com/jazzband/django-constance/blob …

Facilitate renaming Constance in Admin

---

constance/admin.py

If the user of the application customizes various aspects of the Django Admin site through variables like `site_header`, `site_header`, etc. (see Django Admin [docs](https://docs.djangoproject.com/en/1.10/ref/contrib/admin/#adminsite-attributes)) these customizations get lost on the Constance Admin pages. Constance does not pick up these customizations and the Admin templates revert to defaults.
Django Admin includes a function called [`each_context`](https://github.com/django/django/blob/967be82443b5640d61608a89897d8ce2bc44fa54/django/contrib/admin/sites.py#L269) which:
> Returns a dictionary of variables to put in the template context for
> *every* page in the admin site.
This patch uses `each_context` when building the `context` for the `changelist_view` function. This way, Django …

Propagate Django Admin customizations

---

constance/templates/admin/constance/includes/results_list.html

In the default value of a field is of type string and has line breaks (using `\n`), they are not preserved when the *Constance config* page is rendered in the Django Admin. This patch adds the [`linebreaks`](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#linebreaks) filter to the template so that the newlines ('\n') are converted to line break ('\<br\>').

Preserve line breaks in default value

---

constance/admin.py
docs/index.rst
example/cheeseshop/settings.py
tests/settings.py
tests/test_form.py

- Don't ignore additional fields when creating form.  Fixes regression from 2f88a1bff2d3741cd18e1b47fe8c8c1d882795f4
- Added test of form field types
- Added CONSTANCE_ADDITIONAL_FIELDS to example app
- Updated ChoiceField example, the key & value seemed to be the wrong way around?

Additional fields fix

---

constance/templates/admin/constance/includes/results_list.html

Fix for #178. The JavaScript is pretty basic:
```javascript
document.getElementById(...).value = ...
```
Here is how it looks:

Add "Reset to default" feature

---

AUTHORS
constance/management/commands/constance.py
docs/index.rst
tests/test_cli.py
tests/test_utils.py

Require each value to be passed as a separate argument, so we can use the normal field logic to combine them, resolves #186 
see docs https://github.com/jazzband/django-constance/compare/cli_set_datetime?expand=1#diff-caf2a6b8f4947d018f68893c695b5202R276
Also added myself to AUTHORS

Fix handling of MultiValueField's (eg SplitDateTimeField) on the command line. Fixes #186 

---

.travis.yml
tests/urls.py
tox.ini

Fixed Django 2.0 tests due to `django.conf.urls.include` behavior change i.e.
```
django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to django.conf.urls.include()
is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide
the namespace argument to include() instead.
```
Removed pypy for Django 2.0 tests. We cannot use `pypy3` instead (see https://github.com/travis-ci/travis-ci/issues/6277).

Fixed Django 2.0 tests due to `django.conf.urls.include` behavior change. Removed pypy for Django 2.0 tests.

---

constance/management/commands/constance.py
tests/settings.py
tests/storage.py
tests/test_cli.py
tests/test_utils.py

I removed unnecessary `stdout` bytes encode. This PR fixes Django 2.0 tests e.g.:
```
======================================================================
ERROR: test_list (tests.test_cli.CliTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/django-constance/tests/test_cli.py", line 25, in test_list
call_command('constance', 'list', stdout=self.out)
File "/django-constance/.tox/py35-django-master/lib/python3.5/site-packages/django/core/management/__init__.py", line 128, in call_command
return command.execute(*args, **defaults)
File "/django-constance/.tox/py35-django-master/lib/python3.5/site-packages/django/core/management/base.py", line 327, in execute
output = self.handle(*args, **options)
File …
```

Removed unnecessary `stdout` bytes encode.

---

constance/apps.py
tests/settings.py
tests/test_app.py

While running migrations with multiple databases I have noticed that the create_perm signal handler doesn't use the given "using" argument, which means that it always creates the ContentType and Permission in the default database.
The fix is to use the "using" argument on the objects manager with the using method. 
I have also added tests for this, which needed an extra "secondary" database in the settings.py.
This means that every db setup is done twice, which is unnecessary for every other tests, but I don't think that is possible to add a new database to the settings for only one test case.

Fix create_perm in apps.py to use database alias given by the post_migrate signal

---

constance/admin.py
docs/index.rst

This method is used in the `changelist_view` to get the changelist form.
You may want to override this method to serve different forms depending
on the user that make the request. For example:
class MyConstanceAdmin(ConstanceAdmin):
def get_changelist_form(self, request):
if request.user.is_superuser:
return SuperuserForm:
else:
return super(MyConstanceAdmin, self).get_changelist_form(request)
Django's `ModelAdmin` has similar hooks which are pretty useful when you need to allow different groups of users with different privileges to access the admin site.

Add a `get_changelist_form` hook in `ConstanceAdmin`

---

constance/backends/database/__init__.py
constance/backends/redisd.py
constance/signals.py
docs/index.rst

One of the main uses of the config_updated signal is to act accordingly to field changes. Signal is already providing the key and the new value, but it misses the old value so anyone can compare if it was changed.
I'm proposing here to send into the signal the old value as well as the new value, so it allows to compare if the value was changed and act accordingly.
@jezdez Could you please take a look and let me know what you think?

Added the old value to the config_updated signal

---

tests/settings.py

I fixed deprecation warning:
```?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_CONTEXT_PROCESSORS.```

Removed deprecated TEMPLATE_CONTEXT_PROCESSORS setting.

---

.travis.yml
tox.ini

I only have 2.7 and 3.6 on my machine, was helpful to get this in the tox.ini file. 
We need to set the python version explicitly on Travis, though, otherwise, it raises an interpreter not found error.

Add python 3.6 to build matrix

---

constance/admin.py
constance/backends/database/__init__.py
constance/test/utils.py

iter(dict) is equivalent to iter(dict.keys()). Can simply act on the
dict instead. Provides a more concise, Pythonic syntax and avoids an
unnecessary function call.
Inspired by Lennart Regebro's presentation "Prehistoric Patterns in
Python" at PyCon 2017. Available at:
https://www.youtube.com/watch?v=V5-JH23Vk0I

Remove unnecessary calls to dict.keys

---

constance/admin.py
tests/test_admin.py
tox.ini

The setting for CONSTANCE_CONFIG_FIELDSETS should have ordered iterable as values, so use that for ordering.
I've tried to use Django's [`@override_settings`](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#django.test.override_settings) decorators, but it doesn't seem to work so well with projects settings, so I've resorted to the mock library.

Fix #187: Preserve sorting from fieldset config

---

constance/backends/database/__init__.py

Ignore OperationErrors during mget/get to allow migration/test to run.
I intentionally left set unmodified, as it isn't needed during both operation. It should be a reminder to users that they need to run migration.

database: Ignore operation errors (#229)

---

constance/admin.py

Use admin_site property of ModelAdmin, to make sure that the correct list of apps is used.
This should fix #219

Fix for #219

---

docs/index.rst

TEMPLATE_CONTEXT_PROCESSORS is deprecated in Django 1.8. This updates the documentation to match.

Update information on template context processors

---

constance/admin.py
constance/templates/admin/constance/includes/results_list.html

* I added a flag in the context for `DateTime` type
* In the template I use `get_format('DATE_INPUT_FORMATS')[0]` and `get_format('TIME_INPUT_FORMATS')[0]` from Django Admin to format the date and time. I similar pattern is used in for *Now* and *Today* functionality available in the widget.

Fix Reset to default for DateTime, #185

---

constance/admin.py

Account for cases where CONSTANCE_CONFIG_FIELDSETS is not set at all in ConstanceForm validation.

Fix ConstanceForm validation

---

constance/admin.py

`CONSTANCE_CONFIG_FIELDSETS` should be optional (change in `2.1.0` broke it), otherwise nothing could be updated if `CONSTANCE_CONFIG_FIELDSETS` is not defined at all, which should be the most common use case.

Fix `CONSTANCE_CONFIG_FIELDSETS` mismatch issue

---

constance/apps.py
tests/test_app.py

This is an attempt to fix the issue described in #210. What this PR does is add a `CONSTANCE_DBS` setting to the Django settings file. This is an interable that says which databases should be affected by the `django-constance` post-migration signals.
Not sure if this is the best way to fix this, but it seems to work for me ¯\\\_(ツ)_/¯
Totally open to better name suggestions than `CONSTANCE_DBS` :+1:

Workaround to make `django-constance` work in multi-DB project

---

tests/test_admin.py

Changed in https://github.com/django/django/commit/ff05de760cc4ef4c7f188e163c722ec3bc1f0cbf.

Fixed TestAdmin.test_linebreaks() due to linebreaksbr() behavior change on Django 2.1.

---

constance/apps.py

If i change the permission `change_config`'s name to other name and `migrate` i will get this error:
```
django.db.utils.IntegrityError: (1062, "Duplicate entry '2-change_config' for key 'auth_permission_content_type_id_codename_01a
b375a_uniq'")
```

fix bug of can't change permission chang_config's name

---

constance/static/admin/js/constance.js
constance/templates/admin/constance/includes/results_list.html

* Follow-on for #274 by @DmitryKaramin
* Consistent implementation re: `datetime`
* Consistent reset using `DATE_INPUT_FORMAT`, i.e.
- Works whether `USE_L10N` setting is active or not
---
I've been using v2.2.0 and had issues with handling dates.  Stated making my own modifications but then came across #274, which resolves the problem.
This PR makes the solution more consistent, both with the surrounding code as well as the actual reset value format, i.e. brings it into line with `datetime`.

Improve consistency of reset value handling for `date`

---

constance/admin.py

When missing a field mentioned in `CONSTANCE_CONFIG_FIELDSETS` in `CONSTANCE_CONFIG`, the error message is no explicit about the variable.
`AssertionError: CONSTANCE_CONFIG_FIELDSETS contains field(s) that does not exist `
To make the debugging easier, I include the missing variables in the error message
AssertionError: CONSTANCE_CONFIG_FIELDSETS contains field(s) that does not exist: example_field_1

show not existing fields in field_list

---

constance/admin.py

The current behavior of saving files is to save locally using `open` and `MEDIA_ROOT` which doesn't work when your storage is a remote one (eg. S3). Using `default_storage` will use whatever you had configured in your settings.

Use default_storage to save file

---

constance/admin.py

We need to store the actual name of the file, which the storage's save method provides. Otherwise, if we upload a new file with the same name as the already stored file has, the Constance config will keep a link to the old file.

ConstanceForm save method tweak to store the actual filename

---

.gitignore
AUTHORS
constance/admin.py
tests/settings.py
tests/test_admin.py
tests/test_cli.py

The Issue https://github.com/jazzband/django-constance/issues/49 is reproduced when Django setting `USE_TZ = True`

Fixed "can't compare offset-naive and offset-aware datetimes"

---

docs/index.rst

Make "Installation" section of documentation less fraught by only including instructions to install django-constance with the default Redis backend. This will reduce the chances of new users failing to
successfully install the database backend because it needs additional configuration.
Fixes #375.

Simplify documentation installation section.

---

constance/backends/database/__init__.py
tests/test_database.py

It turned out that changes made in #329 led to errors when `set()` method is called simultaneously from different processes. This PR fixes #383 by replicating the logic of `get_or_create()` which previously used in this part of code. Setting the default value now requires 5 database queries which is still an improvement if we compare with the time before #329 when it took 6 queries.

Allow concurrent calls to set() method

---

constance/admin.py
constance/apps.py

Ref #254 
When `CONSTANCE_SUPERUSER_ONLY` is set to False, there is no way of displaying the values without the change permission.
This PR fixes this issue with the new `view_config` permission.

Read-only form with correct perm

---

constance/admin.py

When using a FIPS enabled machine, this line causes the following error because md5 is not allowed.
```
Traceback (most recent call last):
File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib64/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
response = view_func(request, *args, **kwargs)
File …
```

Switch md5 to sha256.

---

constance/admin.py
example/cheeseshop/settings.py
tests/test_admin.py

Normalize newlines from form

---

constance/checks.py

The fix given the possibility that the fieldset could be a dictionary (when it defined as collapsible).
https://django-constance.readthedocs.io/en/latest/#fieldsets-collapsing
```
CONSTANCE_CONFIG = {
'SITE_NAME': ('My Title', 'Website title'),
'SITE_DESCRIPTION': ('', 'Website description'),
'THEME': ('light-blue', 'Website theme'),
}
CONSTANCE_CONFIG_FIELDSETS = {
'General Options': {
'fields': ('SITE_NAME', 'SITE_DESCRIPTION'),
'collapse': True
},
'Theme Options': ('THEME',),
}
```
Currently, if the set is defined as collapsible, there is no way to save changes due to incorrect validation.

Fix for the get_inconsistent_fieldnames() function. The fieldset can be a dictionary, not a tuple.

---

constance/admin.py
example/cheeseshop/urls.py
tests/urls.py

replaced url() functions with newer re_path() function and add path() functions to urls.py files

url() is deprecated in Django 3.1

---

.github/workflows/release.yml
.github/workflows/test.yml
tox.ini

Travis CI has a new pricing model which places limits on open source.
* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
* https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
Many projects are moving to GitHub Actions instead, including Jazzband projects: 
* https://github.com/orgs/jazzband/projects/1
* https://github.com/jazzband-roadies/help/issues/206
This is based on https://github.com/jazzband/contextlib2/pull/26.
TODO:

Migrate to GitHub Actions.

---

constance/admin.py

This is related to #244 and https://github.com/django-admin-tools/django-admin-tools/issues/103.

Add concrete_model class attribute to fake admin model.

---

docs/index.rst

Monospace the `pip install` command in the docs to make it easier to read.

Improve formatting of the pip install command

---

constance/templates/admin/constance/includes/results_list.html

When using a `datetime` field in `CONSTANCE_CONFIG`, it won't be recognized as `datetime` in the template, but as `date`, since `datetime` is a subclass of `date`.
This breaks the "Reset to default" button for `datetime` fields on the admin page.

Fix "Reset to default" for datetime fields

---

docs/backends.rst

Documentation was missing for constance_dbs config.
If you have multiple databases and one of the DBs you have does not apply migrations for `contenttypes` then it is failing during migrating constance. Can be fixed with settings this option. It can be only found in changelog but there was no documentation.
Check #376 for example to the problem that I mentioned.

Add documentation for constance_dbs config

---

constance/backends/redisd.py
constance/settings.py
docs/backends.rst
tests/backends/test_redis.py

Quite often configuration is a rarely updated. And get current value in time is not so important. But redis backend always retrieves a current value.
Due to this simple access to the config has a sudden overhead especially in cycles. Programmer should always remeber about it and cache values manually.
Even a small timeout can drastically increase performance.

Add caching redis backend

---

constance/admin.py
example/cheeseshop/fields.py
example/cheeseshop/settings.py

Default value of custom fields does not work properly with custom fields. 
For example, if i use json field like in my merge request, default value will be serialized with ordinary quotes and it is invalid json and i would not be able to reset to default. Actual value is serialized by from form and is always correct.

Serialize fields according to widget

---

constance/backends/database/apps.py

This ensures that changing DEFAULT_AUTO_FIELD in settings.py doesn't
create migrations for constance.

Add default_auto_field to database backend

---

tox.ini

Fix the error preventing pypy from publishing the package.
Implemented the error log suggestion:
```
WARNING: PendingDeprecationWarning
Support of old-style PyPy config keys will be removed in tox-gh-actions v3.
Please use "pypy-2" and "pypy-3" instead of "pypy2" and "pypy3".
Example of tox.ini:
[gh-actions]
python =
pypy-2: pypy2
pypy-3: pypy3
```
For more details:
- Successful build: https://github.com/pirods/django-constance/runs/6074844048?check_suite_focus=true
- Failing build: https://github.com/jazzband/django-constance/runs/5676961960?check_suite_focus=true
Issue #468

Fix build issues

---

constance/admin.py
constance/checks.py
docs/index.rst
tests/test_admin.py

Suggested fix for #488 
A simple fix that adds support for using a tuple instead of a dictionary for `CONSTANCE_CONFIG_FIELDSETS`. This avoids the need to hash the fieldset header and therefore allows using the `gettext_lazy` function for them. 
---
Along the change itself, I've also included a test and an update to the documentation.

Add support for using gettext in fieldset headers

---

constance/apps.py
constance/backends/database/__init__.py
setup.py
tox.ini

See https://github.com/django/django/commit/8e3b1cf098018b4632de63c359ef6d761e92ec04.

Added support for Django 4.1. 

---

constance/__init__.py
docs/changes.rst

@jazzband/roadies refs https://github.com/jazzband/help/issues/307
Fixes #496 #495 #493

Preparing release 2.9.1

---

constance/admin.py
docs/changes.rst
tests/test_admin.py

Hello. I would like to forward the request to the instance of ConstanceForm, when calling the save method. Help me understand if it is necessary to update any tests.

Forward the request when saving the form

---

docs/backends.rst

Hey, noticed the redundant and and it bugged me 😀

Fix "and and" in backends.rst

---

constance/__init__.py
constance/admin.py
constance/apps.py
constance/checks.py
example/cheeseshop/settings.py
tests/test_checks.py

Solves issue [505](https://github.com/jazzband/django-constance/issues/505) 
Checks are written according to [django docs](https://docs.djangoproject.com/en/3.2/topics/checks/)
Added extra check for extra key. Previous one was only for missing fields.
Added tests
Added some typing.

505-race-condition-caused-by-when-constance-registers-django-checks

---

docs/changes.rst
setup.py
tox.ini

For supported versions of Python: https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django

Add official support for Django 4.2

---

tox.ini

There is an issue with typings in pypi.
asgiref (django dependency) has been recently updated to version 3.7.2 [changelog](https://github.com/django/asgiref/blob/main/CHANGELOG.txt) and there are new typings.
I don`t want to pin asgiref version to 3.7.1 because this is test case for django 3.2. New django versions are not tested on pypy and it is better to use the latest asgiref.

remove pypy from tox tests

---

constance/migrations/0002_migrate_from_old_table.py

https://github.com/jazzband/django-constance/issues/528
Quoted is done correctly now.
I have tested on sqlite, mysql & postgresql

fix migration on mysql

---

.github/workflows/release.yml
.github/workflows/test.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `set-output` to `$GITHUB_OUTPUT`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

ci: Use GITHUB_OUTPUT envvar instead of set-output command

---

constance/backends/database.py
tests/backends/test_database.py

Fix issue #510

---

constance/test/pytest.py
constance/test/unittest.py
tests/test_pytest_overrides.py
tests/test_test_overrides.py

fix: typos

---

.pre-commit-config.yaml
constance/admin.py
constance/backends/database.py
constance/backends/redisd.py
constance/management/commands/constance.py

Use current style to print variables in strings.
credit: tool pyupgrade

chore: migrate to f-string

---

.github/dependabot.yml
.github/workflows/test.yml
setup.py
tox.ini

- drop eol django 3.2 4.0 4.1
- drop eol python 3.7
- drop untested PyPy support
- prepare python 3.12 test
- prepare django 5.1 test
- update GH action dependencies
- add dependabot to maintain GH action dependencies
fixes #540

chore: update supported versions

---

constance/admin.py
constance/templates/admin/constance/change_list.html

fix: django 5.1 removed collapse.js

---

docs/index.rst

```diff
-        to signup for our newletter.
+        to signup for our newsletter.
```

docs/index.rst: Fix typo newsletter

---

tox.ini

Add a check to ensure migrations always reflect the latest changes of `models.py`.
As discussed in #570; feel free to cherry-pick into #571.

Check missing migrations

---

constance/migrations/0003_drop_pickle.py

Error Details
The migration process attempted to apply the migration 0003_drop_pickle but failed with the following traceback:
```bash
Operations to perform:
Target specific migration: 0003_drop_pickle, from constance
Running migrations:
Applying constance.0003_drop_pickle...Traceback (most recent call last):
File "/code/manage.py", line 23, in <module>
main()
File "/code/manage.py", line 19, in main
execute_from_command_line(sys.argv)
File "/code/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
utility.execute()
File "/code/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File …
```

fix: Fixed _pickle.UnpicklingError

---

constance/codecs.py
docs/backends.rst
docs/index.rst
tests/settings.py
tests/storage.py
tests/test_cli.py
tests/test_codecs.py
tests/test_utils.py

Fix #574
@sebastianmanger @lpomfrey This PR should address your problem from #574, could you please review/test it?
cc: @ivan-klass @Natim @camilonova

Collections support

---

constance/migrations/0002_migrate_from_old_table.py

@sergei-iurchenko could you please check this improvement?

Fix exception in 0002 migration

---

.gitignore
constance/migrations/0003_drop_pickle.py

@ivan-klass could you review this, please?
Fix #585. Related #578

Better already migrated detection

---

constance/migrations/0003_drop_pickle.py

Catch UnicodeDecodeError in `is_already_migrated`

---

docs/index.rst
docs/testing.rst

Instead of text "note" use the function which sphinx offers.

fix(docs): use sphinx note function

---

constance/admin.py

Early testing the [upgrade to Django 5.2](https://docs.djangoproject.com/en/dev/releases/5.2/), I'm facing an issue with Django-constance admin:
```
File "/home/runner/work/silvr-app/silvr-app/silvr-app/.venv/lib/python3.12/site-packages/constance/admin.py", line 194, in <module>
admin.site.register([Config], ConstanceAdmin)
File "/home/runner/work/silvr-app/silvr-app/silvr-app/.venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 116, in register
if model._meta.is_composite_pk:
^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Meta' object has no attribute 'is_composite_pk'
```
Indeed, Django last/next version provides [composite primary keys](https://docs.djangoproject.com/en/dev/releases/5.2/#composite-primary-keys) which requires a new Meta on Models.
Due to the fake …

Fix Admin on Django 5.2
