jazzband/django-constance

constance/backends/database/__init__.py

Currently cache doesn't update after we insert new value for key.
I cannot write test for this yet, because of https://github.com/jazzband/django-constance/issues/144

Update cache when key changed

---

tests/test_database.py
tests/test_redis.py

Addresses the https://github.com/jazzband/django-constance/issues/144

Fix backend initialization in tests

---

constance/templates/admin/constance/change_list.html
constance/templates/admin/constance/includes/results_list.html

I'm adding a fieldset structure like the one used in the inlines to improve readability when having multiple fields inside fieldsets.

Improve html layout when using fieldsets

---

constance/__init__.py
constance/backends/database/__init__.py
constance/backends/redisd.py
constance/signals.py
docs/index.rst

I tried to add tests but seems you can only tests signals using Mock.
Please let me know if anything else is needed.

Moved the signal to its own file to avoid import errors. Fixes #158

---

constance/admin.py

Fixed wrong sorting for config. Added sorting for config fieldset

Fixed wrong sorting for config. Added sorting for config fieldset

---

constance/admin.py
constance/management/commands/constance.py
docs/index.rst
example/cheeseshop/settings.py
tests/settings.py
tests/storage.py
tests/test_cli.py
tests/test_form.py
tests/test_utils.py

Squashed version of #164 (originally requested by @jezdez in NZME/django-constance-cli#2), plus fixes from #179

Backport command functonality from django-constance-cli (squashed)

---

constance/admin.py
constance/templates/admin/constance/includes/results_list.html

* Add field name to each config value
* Check field name and use *checked* for checkbox and *value* otherwise
Fix #189

Fix *Reset to default* to work with boolean/checkboxes

---

constance/admin.py
example/cheeseshop/settings.py
tests/urls.py

Removed unused variables and imports.

---

constance/static/admin/css/constance.css
constance/static/admin/js/constance.js
constance/templates/admin/constance/change_list.html
constance/templates/admin/constance/includes/results_list.html

As constance use inline JavaScript to reset field to default, it will be unusable when the site have CSP setup. I've moved inline JS/CSS out to their own files.

Moved inline css/javascripts out to their own files

---

constance/backends/database/__init__.py

As #230 might not fix the issue #229 for all users, this should.

database: Allow running set while database is not created (close #229)

---

MANIFEST.in

Otherwise admin will error if static manifest is enabled

Pack static files into release

---

docs/index.rst

I made a couple of mistakes in #239. This should fix that. I apologize.

Fix link and grammar

---

constance/admin.py
constance/templates/admin/constance/includes/results_list.html
docs/index.rst

I just added the support to upload files.

Added file uploads. Fixes #141 and Fixes #241

---

constance/admin.py
tests/test_admin.py

Add config labels

---

docs/index.rst

PR for the [issue](https://github.com/jazzband/django-constance/issues/270)

Documented use with admin extensions

---

CONTRIBUTING.md
docs/changes.rst

Fix misspelled words in contributing guidelines and changelog. Fix formatting of multi-line changelog entry.

Fix spelling issues in CONTRIBUTING and changelog.

---

docs/index.rst

Fixed docs signals

---

constance/static/admin/js/constance.js

Remove duplicated }

---

constance/static/admin/css/constance.css
constance/templates/admin/constance/includes/results_list.html

Added wrapper like in Django 2 to make results table horizontal scrollable

made results table responsive for Django 2 admin

---

constance/backends/database/__init__.py
tests/test_database.py

Reduced number of DB queries:
* get default: from 6 to 3
* set: from 3 to 2

Optimizations for database backend

---

constance/management/commands/constance.py
docs/index.rst
tests/test_cli.py

issue:
https://github.com/jazzband/django-constance/issues/354

command-to-delete-stale-records

---

.travis.yml

Fixes #385 
It was removed by 590fa02eb30e377da0eda5cc3a84254b839176a7

Put back wheel generation in travis

---

.github/ISSUE_TEMPLATE.md

add django-constance version to issue template

---

constance/checks.py

Lazy checks for pytest

---

constance/templates/admin/constance/change_list.html

Respect other HTML classes added to 'body' by admin templates

---

constance/signals.py

Fix RemovedInDjango40Warning about Signal

---

README.rst

travis -> github actions
Reference:  #435

Fix build badge url

---

constance/templates/admin/constance/change_list.html
constance/templates/admin/constance/includes/results_list.html

Seems like leftovers from xhtml.

fix: html5 does not allow self-closing tags

---

constance/static/admin/js/constance.js

chore: migrate JS to ES2015

---

docs/backends.rst
docs/testing.rst

Some URLs changed permanently.

fix(docs): update links

---

.tx/config

translation service is not available anymore

---

.github/workflows/release.yml

Pin gh-action-pypi-publish version

---

constance/migrations/0003_drop_pickle.py

Follow-up of https://github.com/jazzband/django-constance/pull/576

More safe suppress of pickle-to-json data migration

---

pyproject.toml

This is very useful to have scm as a source of truth

Add setuptools-scm for dynamic version for scm version management

---

.github/workflows/test.yml
pyproject.toml
tox.ini

feat(tests): add python 3.13 to tests

---

docs/index.rst

- improve command line
- update option descriptions according to current code
After
Before

feat(docs): improve command line
